apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingredient-parser-ingress
spec:
  rules:
  - host: ingredient-parser
    http:
      paths:
      - backend:
          serviceName: ingredient-parser-service
          servicePort: 80
